# Generated by Django 3.2.7 on 2021-09-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_imgcart_imgrep'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgrep',
            name='color_palette',
            field=models.CharField(default='', max_length=150),
        ),
    ]
