# Generated by Django 3.2.7 on 2021-09-22 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_imgcart_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgcart',
            name='img',
        ),
    ]
