# Generated by Django 3.2.7 on 2021-09-22 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_remove_imgcart_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgcart',
            name='img',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Cart_Img', to='App.imgrep'),
            preserve_default=False,
        ),
    ]
